import { expect, test } from '@playwright/test'

const post = (request, query, variables) =>
  request.post('/graphql', { data: { query, variables } })

test.describe('SandboxApi GraphQL plugin', () => {
  test('exposes a schema over the /graphql endpoint', async ({ request }) => {
    const response = await post(request, '{ __schema { queryType { name } } }')

    expect(response.ok()).toBeTruthy()

    const body = await response.json()
    expect(body.errors).toBeUndefined()
    expect(body.data.__schema.queryType.name).toBe('Query')
  })

  test('exposes the users-permissions types generated by shadow CRUD', async ({
    request,
  }) => {
    const response = await post(
      request,
      '{ __type(name: "UsersPermissionsUser") { name kind } }',
    )

    const body = await response.json()
    expect(body.errors).toBeUndefined()
    expect(body.data.__type).toMatchObject({
      name: 'UsersPermissionsUser',
      kind: 'OBJECT',
    })
  })

  test('reports an error for an unknown field instead of crashing', async ({
    request,
  }) => {
    const response = await post(request, '{ thisFieldDoesNotExist }')
    const body = await response.json()

    expect(body.errors?.length).toBeGreaterThan(0)
    expect(body.errors[0].message).toContain('thisFieldDoesNotExist')
  })
})
